# An example configuration for a KaMinPar experiment.

# Pick a system for which the jobfiles should be generated:
# - generic          # any Linux system
# - background       # any Linux system, run experiment via "nohup & disown"
# - spack            # any Linux system with a Spack installation, activate specified Spack
#                      environment and run experiment via background
# - i10-exclusive    # i10 compute servers, run experiment via "exclusive" + background
# - i10-nonexclusive # i10 compute servers, run experiment via "nonexclusive" + background
#
system = "generic"

# Name of the Spack environment to activate before running the experiment. Must be specified if
# Spack is used as the system option.
#
# spack-environment = "KaMinPar"

# Pick a "call wrapper" that should be used to invoke KaMinPar.
# - none             # do not run with any call wrapper
# - taskset          # use taskset to limit CPU affinity
# - mpi              # use mpirun to execute parallel jobs.
#
call-wrapper = "none"

# Path of the GNU Time command, which displays information about the resources
# used by a program. If the path is not defined, the time-wrapper is not used.
#
# time-cmd = "/usr/bin/time"

[Graph-Compression]
graphs = "/path/to/benchmark-set/"
processes = [1]
threads = [4, 64]
ks = [8, 64, 128, 1024, 30000]
epsilons = [0.03]
seeds = [1, 2, 3, 4, 5]

[Graph-Compression.Reference]
git-url = "https://github.com/KaHIP/KaMinPar.git"
# Optional: specify git branch or commit [default: main]
branch = "main"
# Optional: specify build target (KaMinPar, dKaMinPar, or a benchmark) [default: KaMinPar]
target = "KaMinPar"
compile-flags = [
    "-DKAMINPAR_ENABLE_HEAP_PROFILING=ON",
    "-DKAMINPAR_64BIT_EDGE_IDS=On",
    "-DKAMINPAR_64BIT_WEIGHTS=On",
]
args = ["--node-order external-deg-buckets"]
per-k-args = { 30000 = ["-P largek"] }

[Graph-Compression.Compression]
git-url = "https://github.com/KaHIP/KaMinPar.git"
compile-flags = [
    "-DKAMINPAR_ENABLE_HEAP_PROFILING=ON",
    "-DKAMINPAR_64BIT_EDGE_IDS=On",
    "-DKAMINPAR_64BIT_WEIGHTS=On",
]
args = ["--node-order external-deg-buckets", "--compress"]
per-k-args = { 30000 = ["-P largek"] }
